"""Phase 1: Firmen, API-Schlüssel, Zertifikate, Vorlagen, Pässe

Revision ID: 0001
Revises: 
Create Date: 2026-10-03 22:20:14.201022

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0001'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('certificates',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('pass_type_identifier', sa.String(length=200), nullable=False),
    sa.Column('team_identifier', sa.String(length=20), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('pass_type_identifier')
    )
    op.create_table('tenants',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('organization_name', sa.String(length=200), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('plan', sa.String(length=20), nullable=False),
    sa.Column('certificate_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['certificate_id'], ['certificates.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('api_keys',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('prefix', sa.String(length=16), nullable=False),
    sa.Column('secret_hash', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('prefix')
    )
    with op.batch_alter_table('api_keys', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_api_keys_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('templates',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('approved_version_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('templates', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_templates_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('passes',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('template_id', sa.String(length=36), nullable=False),
    sa.Column('serial_number', sa.String(length=100), nullable=False),
    sa.Column('data', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('download_token', sa.String(length=64), nullable=False),
    sa.Column('auth_token_enc', sa.Text(), nullable=False),
    sa.Column('idempotency_key', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['template_id'], ['templates.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('download_token'),
    sa.UniqueConstraint('tenant_id', 'idempotency_key'),
    sa.UniqueConstraint('tenant_id', 'serial_number')
    )
    with op.batch_alter_table('passes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_passes_template_id'), ['template_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_passes_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('template_versions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('template_id', sa.String(length=36), nullable=False),
    sa.Column('number', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('pass_json', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('review_note', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['template_id'], ['templates.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('template_id', 'number')
    )
    with op.batch_alter_table('template_versions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_template_versions_template_id'), ['template_id'], unique=False)

    # Erst jetzt existiert template_versions: Verweis auf die freigegebene Version nachtragen.
    with op.batch_alter_table('templates', schema=None) as batch_op:
        batch_op.create_foreign_key('fk_template_approved_version', 'template_versions',
                                    ['approved_version_id'], ['id'])

    op.create_table('template_files',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('version_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('data', sa.LargeBinary(), nullable=False),
    sa.ForeignKeyConstraint(['version_id'], ['template_versions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('version_id', 'name')
    )
    with op.batch_alter_table('template_files', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_template_files_version_id'), ['version_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('template_files', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_template_files_version_id'))

    op.drop_table('template_files')
    with op.batch_alter_table('templates', schema=None) as batch_op:
        batch_op.drop_constraint('fk_template_approved_version', type_='foreignkey')
    with op.batch_alter_table('template_versions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_template_versions_template_id'))

    op.drop_table('template_versions')
    with op.batch_alter_table('passes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_passes_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_passes_template_id'))

    op.drop_table('passes')
    with op.batch_alter_table('templates', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_templates_tenant_id'))

    op.drop_table('templates')
    with op.batch_alter_table('api_keys', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_api_keys_tenant_id'))

    op.drop_table('api_keys')
    op.drop_table('tenants')
    op.drop_table('certificates')
    # ### end Alembic commands ###
