"""Zertifikate: eigene Zertifikate von Firmen (owner_tenant_id) und festes Zertifikat je Pass

Revision ID: 0005
Revises: 0004
Create Date: 2026-10-04 09:06:12.511348

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0005'
down_revision: Union[str, Sequence[str], None] = '0004'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('certificates', schema=None) as batch_op:
        batch_op.add_column(sa.Column('owner_tenant_id', sa.String(length=36), nullable=True))
        batch_op.create_index(batch_op.f('ix_certificates_owner_tenant_id'), ['owner_tenant_id'], unique=False)
        batch_op.create_foreign_key('fk_certificate_owner_tenant', 'tenants', ['owner_tenant_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('passes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('certificate_id', sa.String(length=36), nullable=True))
        batch_op.create_index(batch_op.f('ix_passes_certificate_id'), ['certificate_id'], unique=False)
        batch_op.create_foreign_key('fk_pass_certificate', 'certificates', ['certificate_id'], ['id'])

    # Bisherige Pässe wurden mit dem aktuellen Zertifikat ihrer Firma ausgegeben - das festhalten.
    op.execute("UPDATE passes SET certificate_id = "
               "(SELECT certificate_id FROM tenants WHERE tenants.id = passes.tenant_id) WHERE certificate_id IS NULL")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('passes', schema=None) as batch_op:
        # WARNING: constraint name is None; this directive will fail as
        # rendered.  Add a name, or use a naming convention; see
        # https://alembic.sqlalchemy.org/en/latest/naming.html
        batch_op.drop_constraint('fk_pass_certificate', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_passes_certificate_id'))
        batch_op.drop_column('certificate_id')

    with op.batch_alter_table('certificates', schema=None) as batch_op:
        batch_op.drop_constraint('fk_certificate_owner_tenant', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_certificates_owner_tenant_id'))
        batch_op.drop_column('owner_tenant_id')

    # ### end Alembic commands ###
