"""Firmen merken sich ihr Standard-Zertifikat (Rückfall beim Abschalten des eigenen)

Revision ID: 0006
Revises: 0005
Create Date: 2026-10-04 09:44:44.722032

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0006'
down_revision: Union[str, Sequence[str], None] = '0005'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tenants', schema=None) as batch_op:
        batch_op.add_column(sa.Column('standard_certificate_id', sa.String(length=36), nullable=True))
        batch_op.create_foreign_key('fk_tenant_standard_certificate', 'certificates', ['standard_certificate_id'], ['id'])

    # Bisher zugeordnete Standard-Zertifikate übernehmen
    op.execute("UPDATE tenants SET standard_certificate_id = certificate_id WHERE certificate_id IN "
               "(SELECT id FROM certificates WHERE owner_tenant_id IS NULL)")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tenants', schema=None) as batch_op:
        batch_op.drop_constraint('fk_tenant_standard_certificate', type_='foreignkey')
        batch_op.drop_column('standard_certificate_id')

    # ### end Alembic commands ###
