"""Betrieb: Massenausgabe, API-Protokoll, Rate-Limits, Tagesverbrauch, Systemzustand, Ankündigungen, Zertifikatsanfragen

Revision ID: 0007
Revises: 0006
Create Date: 2026-10-04 09:48:03.869152

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0007'
down_revision: Union[str, Sequence[str], None] = '0006'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('announcements',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('level', sa.String(length=10), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('api_request_log',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('key_prefix', sa.String(length=16), nullable=False),
    sa.Column('method', sa.String(length=10), nullable=False),
    sa.Column('path', sa.String(length=300), nullable=False),
    sa.Column('status', sa.Integer(), nullable=False),
    sa.Column('duration_ms', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('api_request_log', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_api_request_log_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_api_request_log_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('rate_counters',
    sa.Column('bucket', sa.String(length=120), nullable=False),
    sa.Column('window', sa.Integer(), nullable=False),
    sa.Column('count', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('bucket', 'window')
    )
    op.create_table('system_state',
    sa.Column('key', sa.String(length=80), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('certificate_requests',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('owner_tenant_id', sa.String(length=36), nullable=True),
    sa.Column('label', sa.String(length=200), nullable=False),
    sa.Column('key_enc', sa.Text(), nullable=False),
    sa.Column('csr_pem', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['owner_tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('certificate_requests', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_certificate_requests_owner_tenant_id'), ['owner_tenant_id'], unique=False)

    op.create_table('usage_daily',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('day', sa.String(length=10), nullable=False),
    sa.Column('active', sa.Integer(), nullable=False),
    sa.Column('issued', sa.Integer(), nullable=False),
    sa.Column('installed', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'day')
    )
    with op.batch_alter_table('usage_daily', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_usage_daily_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('bulk_issues',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('template_id', sa.String(length=36), nullable=False),
    sa.Column('created_by', sa.String(length=200), nullable=False),
    sa.Column('filename', sa.String(length=200), nullable=False),
    sa.Column('rows', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('send_emails', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('total', sa.Integer(), nullable=False),
    sa.Column('done', sa.Integer(), nullable=False),
    sa.Column('failed', sa.Integer(), nullable=False),
    sa.Column('results', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['template_id'], ['templates.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('bulk_issues', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_bulk_issues_tenant_id'), ['tenant_id'], unique=False)

    with op.batch_alter_table('tenants', schema=None) as batch_op:
        batch_op.add_column(sa.Column('quota_notice', sa.String(length=20), nullable=False, server_default=''))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tenants', schema=None) as batch_op:
        batch_op.drop_column('quota_notice')

    with op.batch_alter_table('bulk_issues', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_bulk_issues_tenant_id'))

    op.drop_table('bulk_issues')
    with op.batch_alter_table('usage_daily', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_usage_daily_tenant_id'))

    op.drop_table('usage_daily')
    with op.batch_alter_table('certificate_requests', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_certificate_requests_owner_tenant_id'))

    op.drop_table('certificate_requests')
    op.drop_table('system_state')
    op.drop_table('rate_counters')
    with op.batch_alter_table('api_request_log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_api_request_log_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_api_request_log_created_at'))

    op.drop_table('api_request_log')
    op.drop_table('announcements')
    # ### end Alembic commands ###
